### ISSUE TITLE
Missing extension @ install

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#16]
![missing_extension](https://user-images.githubusercontent.com/3336728/63202888-ac4e0d80-c094-11e9-87f3-493184d12ce5.jpg)

Got this during installation.
Which extension is missing?

 Tested on: https://github.com/nivocart/nivocart/commit/084b075c65cffad3742b1c4450368ec2aafedcbf

**Comment by nivocart** [comment]
This is the "openssl_encrypt" function.
Which PHP version are you using?

**Comment by Tangol** [comment]
I'm using **PHP 7.0.33**.
But why doesn't it say **openssl_encrypt** and only shows an empty space?

**Comment by nivocart** [comment]
It shows an empty space because the code calls the function directly, which it can't find.
For that reason the function name is not displaying.
I can fix this by re-instating "mcrypt-encrypt", less secure, for php 7.0.x.
"openssl-encrypt" is required only starting from php 7.1.x as "mcrypt-encrypt" is then deprecated.
Saying that, you should be able to get "openssl-encrypt" for php 7.0.x if it what you're going to use in the long term, because it is far more secure and that's why "mcrypt-encrypt" is being deprecated.
Still, I am going to put it back for compatibility reasons.

**Comment by Tangol** [comment]
Issue fixed. 
Can be closed.
