### ISSUE TITLE
Blog Module & Blog System

### ISSUE THREAD

**Issue by Tangol** [nivocart/nivocart#6]
I've noticed that we have 2 **Blog** settings: 
1. Blog Module (found under Extensions > Modules > Blog)
2. Blog System (found under Extensions > Modifications > Blog System)

![blog_module](https://user-images.githubusercontent.com/3336728/49393687-a698dd80-f73a-11e8-8897-b1c950e019aa.png)

I've installed both, but when I try to access the **Blog Module/Blog Category** settings, I get the following error:

![blog_module_settings](https://user-images.githubusercontent.com/3336728/49393728-c0d2bb80-f73a-11e8-835d-a7f30d177ea6.png)

What's the deal with that?

Tested on https://github.com/nivocart/nivocart/commit/90c68a70b6b9a1f5a6ef3d54ca4e3b6742e6668c

**Comment by nivocart** [comment]
Ah Yes. The new Blog is **optional**, database tables are not present at install, because it is a **modification**. In order to use it, you must first Install "Blog" under Modification as this will create the tables required, the layout routes and the Seo-Urls.
Then permissions must be granted in User Groups.
Only then the module "Blog" will be available.

**Comment by nivocart** [comment]
I could not reproduce this error.

If you still have the error, check the DB for the following tables:

'blog_article', 'blog_article_description', 'blog_article_description_additional',
'blog_article_product_related', 'blog_article_to_category',
'blog_article_to_layout', 'blog_article_to_store',
'blog_author', 'blog_author_description',
'blog_category', 'blog_category_description',
'blog_category_to_layout', 'blog_category_to_store',
'blog_comment', 'blog_related_article', 'blog_view'
